routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DataKaryawanController;
use App\Http\Controllers\Konfigurasi\MenuController;
use App\Http\Controllers\Konfigurasi\RoleController;
use App\Http\Controllers\MasterData\JabatanController;
use App\Http\Controllers\Konfigurasi\UserListController;
use App\Http\Controllers\Konfigurasi\AksesRoleController;
use App\Http\Controllers\MasterData\TempatKerjaController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::group(['prefix' => 'konfigurasi', 'as' => 'konfigurasi.'], function () {
        Route::resource('user-list', UserListController::class)->parameters(['user-list' => 'user']);
        Route::put('menu/sort', [MenuController::class, 'sort'])->name('menu.sort');
        Route::resource('menu', MenuController::class);
        Route::resource('roles', RoleController::class);
        Route::get('akses-role/{role}/role', [AksesRoleController::class, 'getPermissionByRole']);
        Route::resource('akses-role', AksesRoleController::class)->except(['create', 'store', 'delete'])->parameters(['akses-role' => 'role']);
    });

    Route::group(['prefix' => 'master-data', 'as' => 'master-data.'], function () {
        Route::resource('jabatan', JabatanController::class);
        Route::resource('tempat-kerja', TempatKerjaController::class);
    });

    Route::resource('data-karyawan', DataKaryawanController::class);
});

require __DIR__ . '/auth.php';

app/Models/Konfigurasi/Menu.php
<?php

namespace App\Models\Konfigurasi;

use App\Models\Permission;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Menu extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function subMenus()
    {
        return $this->hasMany(Menu::class, 'parent_id');
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class, 'menu_permission', 'menu_id', 'permission_id');
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', 1);
    }
}

app/Models/Konfigurasi/MenuPermission.php
<?php

namespace App\Models\Konfigurasi;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuPermission extends Model
{
    use HasFactory;
}

app/Http/Controllers/Konfigurasi/AksesRoleController.php
<?php

namespace App\Http\Controllers\Konfigurasi;

use App\Models\Role;
use Illuminate\Http\Request;
use App\Models\Konfigurasi\Menu;
use App\Http\Controllers\Controller;
use App\DataTables\Konfigurasi\RoleDataTable;

class AksesRoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(RoleDataTable $roleDataTable)
    {
        return $roleDataTable->render('konfigurasi.akses-role.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Role $role)
    {
        //
    }

    private function getMenus()
    {
        return Menu::with('permissions', 'subMenus.permissions')->whereNull('parent_id')->get();
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Role $role)
    {
        $getRole = Role::where('id', '!=', $role->id)->get();
        return view('konfigurasi.akses-role.form', [
            'data'      => $role,
            'action'    => route('konfigurasi.akses-role.update', $role->id),
            'menu'      => $this->getMenus(),
            'role'      => $getRole
        ]);
    }

    public function getPermissionByRole(Role $role)
    {
        return view('konfigurasi.akses-role.list-menu', [
            'data'  => $role,
            'menu'  => $this->getMenus()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Role $role)
    {
        $role->syncPermissions($request->permission);

        return responseSuccess(true);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Role $role)
    {
        return response()->json([
            'status'    => 'error',
            'message'   => 'Data Cannot Deleted!'
        ]);
    }
}

app/Http/Controllers/Konfigurasi/MenuController.php
<?php

namespace App\Http\Controllers\Konfigurasi;

use App\Models\Permission;
use Illuminate\Http\Request;
use App\Models\Konfigurasi\Menu;
use App\Traits\HasMenuPermission;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\DataTables\Konfigurasi\MenuDataTable;
use App\Http\Requests\Konfigurasi\MenuRequest;
use Illuminate\Support\Testing\Fakes\BatchFake;
use App\Repositories\Konfigurasi\MenuRepository;

class MenuController extends Controller
{
    use HasMenuPermission;

    private MenuRepository $repository;
    // public function __construct(private MenuRepository $repository)
    public function __construct(MenuRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(MenuDataTable $menuDataTable)
    {
        return $menuDataTable->render('konfigurasi.menu.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Menu $menu)
    {
        // $this->authorize('create konfigurasi/menu');
        return view('konfigurasi.menu.form', [
            'action'    => route('konfigurasi.menu.store'),
            'data'      => $menu,
            'main_menu' => $this->repository->getMainMenus()
        ]);
    }

    private function fillData(MenuRequest $request, Menu $menu)
    {
        $menu->fill($request->validated());
        $menu->fill([
            'icon'      => $request->icon,
            'parent_id' => $request->parent_id
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(MenuRequest $request, Menu $menu)
    {
        DB::beginTransaction();
        try {
            // $this->authorize('create konfigurasi/menu');
            $this->fillData($request, $menu);
            $menu->save();

            foreach ($request->permissions ?? [] as $val) {
                $permission = Permission::create(['name' => $val . " {$menu->url}"]);
                $permission->menus()->attach($menu);
            }
            DB::commit();
        } catch (\Throwable $th) {
            DB::rollBack();

            return responseError($th);
        }

        return responseSuccess();
    }

    /**
     * Display the specified resource.
     */
    public function show(Menu $menu)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Menu $menu)
    {
        // $this->authorize('update konfigurasi/menu');
        return view('konfigurasi.menu.form', [
            'action'    => route('konfigurasi.menu.update', $menu->id),
            'data'      => $menu,
            'main_menu' => $this->repository->getMainMenus()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(MenuRequest $request, Menu $menu)
    {
        // $this->authorize('update konfigurasi/menu');
        $this->fillData($request, $menu);
        if ($request->level_menu == 'main_menu') {
            $menu->parent_id = null;
        }
        $menu->save();

        return responseSuccess(true);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Menu $menu)
    {
        //
    }
}

app/Http/Controllers/Konfigurasi/RoleController.php
<?php

namespace App\Http\Controllers\Konfigurasi;

use App\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\Konfigurasi\RoleDataTable;
use App\Http\Requests\Konfigurasi\RoleRequest;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(RoleDataTable $roleDataTable)
    {
        return $roleDataTable->render('konfigurasi.role.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('konfigurasi.role.form', [
            'data'      => new Role,
            'action'    => route('konfigurasi.roles.store')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(RoleRequest $request)
    {
        $role = new Role($request->validated());
        $role->save();

        return responseSuccess();
    }

    /**
     * Display the specified resource.
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Role $role)
    {
        $action = route('konfigurasi.roles.update', $role->id);
        return view('konfigurasi.role.form', [
            'data'      => $role,
            'action'    => $action
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(RoleRequest $request, Role $role)
    {
        $role->fill($request->validated());
        $role->save();

        return responseSuccess(true); // true:is_edit
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Role $role)
    {
        $role->delete();
        return responseSuccessDelete();
    }
}

app/Http/Controllers/Konfigurasi/UserListController.php
<?php

namespace App\Http\Controllers\Konfigurasi;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\Konfigurasi\UserDataTable;
use App\Http\Requests\Konfigurasi\UserListRequest;

class UserListController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(UserDataTable $userDataTable)
    {
        return $userDataTable->render('konfigurasi.user-list.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('konfigurasi.user-list.form', [
            'data'      => new User(),
            'action'    => route('konfigurasi.user-list.store'),
            'role'      => Role::get()->pluck('name')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(UserListRequest $request, User $user)
    {
        $user->fill($request->only(['name', 'email']));
        $user->password = bcrypt($request->password);
        $user->markEmailAsVerified();

        $user->save();
        $user->assignRole($request->role);

        return responseSuccess();
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        return view('konfigurasi.user-list.form', [
            'data'      => $user,
            'action'    => route('konfigurasi.user-list.update', $user->id),
            'role'      => Role::get()->pluck('name')
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UserListRequest $request, User $user)
    {
        $user->fill($request->only(['name', 'email']));
        $user->password = bcrypt($request->password);

        $user->save();
        $user->syncRoles($request->role);

        return responseSuccess(true);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        $response = response()->json([
            'status'    => 'error',
            'message'   => 'Data Cannot Deleted!'
        ]);
        if ($user->id <> 1) {
            $user->delete();
            $response = responseSuccessDelete();
        }
        return $response;
    }
}

app/View/Components/MasterLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class MasterLayout extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('layouts.master');
    }
}

resources/views/konfigurasi/menu/form.blade.php
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <div class="modal-title">Menu
                <small class="subtitle-info">Form Data</small>
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {{-- <form action="{{ $action }}" method="post" app-link="default" id="form" autocomplete="off"> --}}
            <form action="{{ $action }}" method="POST" id="form-action" autocomplete="off">
                @csrf
                @if ($data->id)
                    @method('PUT')
                @endif
                {{-- <input type="hidden" class="form-control" id="id" name="id" aria-label="" value="{{ $data->id }}"> --}}
                <div class="mb-3 row">
                    <label for="name" class="col-md-3 required form-label">Name</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" id="name" name="name" aria-label="Menu"
                            value="{{ $data->name }}">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="target" class="col-md-3 required form-label">Target URL</label>
                    <div class="col-md-9">
                        {{-- <input type="text" class="form-control" id="url" name="url" aria-label="Target URL" data-validation="required|min-length:3|letter|unique" value="{{ $data->url }}""> --}}
                        <input type="text" class="form-control" id="url" name="url" aria-label="Target URL"
                            value="{{ $data->url }}"">
                    </div>
                </div>
                <div class=" mb-3 row">
                    <label for="icon" class="col-md-3 form-label">Icon</label>
                    <div class="col-md-5">
                        <div class="input-group iconpicker-container">
                            <input type="text" class="form-control" id="icon" name="icon" aria-label="Icon"
                                value="{{ $data->icon }}">
                        </div>
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="level_menu" class="col-md-3 form-label">Level Menu</label>
                    <div class="col-md-9">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="level_menu" id="level_menu1"
                                value="main_menu" {{ !$data->parent_id ? 'checked' : '' }}>
                            <label class="form-check-label" for="level_menu1">
                                Main Menu
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="level_menu" id="level_menu2"
                                value="sub_menu" {{ $data->parent_id ? 'checked' : '' }}>
                            <label class="form-check-label" for="level_menu2">
                                Sub Menu
                            </label>
                        </div>
                    </div>
                </div>
                <div class="mb-3 row {{ !$data->parent_id ? 'd-none' : '' }}" id="main-menu-wrapper">
                    <label for="parent_id" class="col-md-3 form-label">Main Menu</label>
                    <div class="col-md-9">
                        <select name="parent_id" id="parent_id" class="form-control select2">
                            <option value="">Select Main Menu</option>
                            @foreach ($main_menu as $mm)
                                <option value="{{ $mm->id }}" {{ $data->parent_id == $mm->id ? 'selected' : '' }}>
                                    {{ $mm->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                @if (request()->routeIs('konfigurasi.menu.create'))
                    <div class="mb-3 row">
                        <label for="permissions" class="col-md-3">Permissions</label>
                        <div class="col-md-9">
                            <div class="row">
                                @foreach (['read', 'create', 'update', 'delete'] as $item)
                                    <div class="mb-3 col-md-3">
                                        <div class="form-check">
                                            <input type="checkbox" name="permissions[]"
                                                id="permissions{{ $item }}" class="form-check-input"
                                                value="{{ $item }}">
                                            <label class="form-check-label"
                                                for="permissions{{ $item }}">{{ ucfirst($item) }}</label>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                @endif
                <div class="mb-3 row">
                    <label for="orders" class="col-md-3 required form-label">Order</label>
                    <div class="col-md-5">
                        {{-- <input type="text" class="form-control" id="orders" name="orders" aria-label="Urutan" data-validation="required|numeric" value="{{ $data->orders }}"> --}}
                        <input type="text" class="form-control" id="orders" name="orders" aria-label="Urutan"
                            value="{{ $data->orders }}">
                    </div>
                </div>
                <div class="modal-footer">
                    {{-- <div class="modal-footer-info">
                            <i class="fa-info-circle" data-appinity-tooltip="right"></i>
                        </div> --}}
                    <button type="button" class="btn btn-theme" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-app">Save</button>
                    {{-- <button type="submit" class="btn btn-app" form="form">Save</button> --}}
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/konfigurasi/menu/index.blade.php
<x-master-layout>
    <div class="panel-content p-3">
        <div class="card">
            <div class="card-header fw-bold"> <a href="javascript:;"> Konfigurasi</a> / Menu</div>
            <div class="card-body">
                @can('create konfigurasi/menu')
                    <div class="mb-3 appinityTable-action-button text-start">
                        <div class="btn-group" role="group">
                            <a href="{{ route('konfigurasi.menu.create') }}" class="btn btn-app btn-add">
                                <i class="fa-plus"></i><span>Add Menu</span>
                            </a>
                            @can('sortsss konfigurasi/menu')
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn btn-app dropdown-toggle" data-bs-toggle="dropdown"
                                        aria-expanded="false"></button>
                                    <ul class="dropdown-menu dropdown-menu-end">
                                        <li>
                                            <a href="{{ route('konfigurasi.menu.sort') }}"
                                                class="dropdown-item dropdown-item-icon sort">
                                                <i class="fa-list"></i>Sort Menu
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            @endcan
                        </div>
                    </div>
                @endcan

                <div id="datatable" data-table="menu-table" class="table-responsive">
                    {!! $dataTable->table() !!}
                </div>
            </div>
        </div>
        <div aria-hidden="" tabindex="-1" id="modal-add" class="modal fade"></div>

        {{-- <div aria-hidden="true" tabindex="-1" id="modal-sort" class="modal fade">
            <div class="modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">Menu<small>Urutkan Menu</small></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer"><button type="button" class="btn btn-theme" data-bs-dismiss="modal">Batal</button>
                        <button type="button" class="btn btn-app" id="save-sort">Simpan</button>
                    </div>
                </div>
            </div>
        </div> --}}
    </div>
    @push('js')
        {!! $dataTable->scripts() !!}
        <script>
            $(document).on('change', '[name="level_menu"]', function() {
                if (this.value == 'sub_menu') {
                    $('#main-menu-wrapper').removeClass('d-none')
                } else {
                    $('#main-menu-wrapper').addClass('d-none')
                }
            });

            $(document).on('click', '.sort', function(e) {
                e.preventDefault()

                handleAjax(this.href, 'put')
                    .onSuccess(function(res) {
                        window.location.reload()
                    }, false).execute();
            });
        </script>
    @endpush
</x-master-layout>