routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DataKaryawanController;
use App\Http\Controllers\Konfigurasi\MenuController;
use App\Http\Controllers\Konfigurasi\RoleController;
use App\Http\Controllers\MasterData\JabatanController;
use App\Http\Controllers\Konfigurasi\UserListController;
use App\Http\Controllers\Konfigurasi\AksesRoleController;
use App\Http\Controllers\MasterData\TempatKerjaController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::group(['prefix' => 'konfigurasi', 'as' => 'konfigurasi.'], function () {
        Route::resource('user-list', UserListController::class)->parameters(['user-list' => 'user']);
        Route::put('menu/sort', [MenuController::class, 'sort'])->name('menu.sort');
        Route::resource('menu', MenuController::class);
        Route::resource('roles', RoleController::class);
        Route::get('akses-role/{role}/role', [AksesRoleController::class, 'getPermissionByRole']);
        Route::resource('akses-role', AksesRoleController::class)->except(['create', 'store', 'delete'])->parameters(['akses-role' => 'role']);
    });

    Route::group(['prefix' => 'master-data', 'as' => 'master-data.'], function () {
        Route::resource('jabatan', JabatanController::class);
        Route::resource('tempat-kerja', TempatKerjaController::class);
    });

    Route::resource('data-karyawan', DataKaryawanController::class);
});

require __DIR__ . '/auth.php';

app/Models/MasterData/Jabatan.php
<?php

namespace App\Models\MasterData;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Models/MasterData/TempatKerja.php
<?php

namespace App\Models\MasterData;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TempatKerja extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
}

app/Http/Controllers/MasterData/JabatanController.php
<?php

namespace App\Http\Controllers\MasterData;

use Illuminate\Http\Request;
use App\Models\MasterData\Jabatan;
use App\Http\Controllers\Controller;
use App\DataTables\MasterData\JabatanDataTable;
use App\Http\Requests\MasterData\JabatanRequest;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(JabatanDataTable $jabatanDataTable)
    {
        return $jabatanDataTable->render('master-data.jabatan.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('master-data.jabatan.form', [
            'data'      => new Jabatan,
            'action'    => route('master-data.jabatan.store')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(JabatanRequest $request)
    {
        $jabatan = new Jabatan($request->validated());
        $jabatan->save();

        return responseSuccess();
    }

    /**
     * Display the specified resource.
     */
    public function show(Jabatan $jabatan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Jabatan $jabatan)
    {
        $action = route('master-data.jabatan.update', $jabatan->id);
        return view('master-data.jabatan.form', [
            'data'      => $jabatan,
            'action'    => $action
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(JabatanRequest $request, Jabatan $jabatan)
    {
        $jabatan->fill($request->validated());
        $jabatan->save();

        return responseSuccess(true);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Jabatan $jabatan)
    {
        $jabatan->delete();
        return responseSuccessDelete();
    }
}

app/Http/Controllers/MasterData/TempatKerjaController.php
<?php

namespace App\Http\Controllers\MasterData;

use Illuminate\Http\Request;
use App\Models\MasterData\TempatKerja;
use App\Http\Controllers\Controller;
use App\DataTables\MasterData\TempatKerjaDataTable;
use App\Http\Requests\MasterData\TempatKerjaRequest;

class TempatKerjaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(TempatKerjaDataTable $tempatKerjaDataTable)
    {
        return $tempatKerjaDataTable->render('master-data.tempat-kerja.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('master-data.tempat-kerja.form', [
            'data'      => new TempatKerja,
            'action'    => route('master-data.tempat-kerja.store')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(TempatKerjaRequest $request)
    {
        $tempatKerja = new TempatKerja($request->validated());
        $tempatKerja->save();

        return responseSuccess();
    }

    /**
     * Display the specified resource.
     */
    public function show(TempatKerja $tempatKerja)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(TempatKerja $tempatKerja)
    {
        $action = route('master-data.tempat-kerja.update', $tempatKerja->id);
        return view('master-data.tempat-kerja.form', [
            'data'      => $tempatKerja,
            'action'    => $action
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(TempatKerjaRequest $request, TempatKerja $tempatKerja)
    {
        $tempatKerja->fill($request->validated());
        $tempatKerja->save();

        return responseSuccess(true);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(TempatKerja $tempatKerja)
    {
        $tempatKerja->delete();
        return responseSuccessDelete();
    }
}

app/View/Components/MasterLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class MasterLayout extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('layouts.master');
    }
}

resources/views/master-data/tempat-kerja/form.blade.php
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <div class="modal-title">Tempat Kerja
                <small class="subtitle-info">Form Data</small>
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{{ $action ?? null }}" method="POST" id="form-action" autocomplete="off">
                @csrf
                @if ($data->id)
                    @method('PUT')
                @endif
                <div class="mb-3 row">
                    <label for="name" class="col-md-3 required form-label">Tempat Kerja</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" id="tempat_kerja" name="tempat_kerja"
                            aria-label="Tempat Kerja" value="{{ $data->tempat_kerja }}">
                    </div>
                </div>

                <div class="modal-footer">
                    @if ($action)
                        <button type="button" class="btn btn-theme" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-app">Save</button>
                    @endif
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/master-data/tempat-kerja/index.blade.php
<x-master-layout>
    <div class="panel-content p-3">
        <div class="card">
            <div class="card-header fw-bold"> <a href="javascript:;"> Master Data</a> / Tempat Kerja</div>
            <div class="card-body">
                @can('create master-data/tempat-kerja')
                    <div class="mb-3 appinityTable-action-button text-start">
                        <div class="btn-group" role="group">
                            <a href="{{ route('master-data.tempat-kerja.create') }}" class="btn btn-app btn-add"
                                app-link="default"><i class="fa-plus"></i><span>Add Tempat Kerja</span></a>
                        </div>
                    </div>
                @endcan

                <div id="datatable" data-table="tempatkerja-table" class="table-responsive">
                    {!! $dataTable->table() !!}
                </div>
            </div>
        </div>
        <div aria-hidden="true" tabindex="-1" id="modal-add" class="modal fade"></div>
    </div>
    @push('js')
        {!! $dataTable->scripts() !!}
    @endpush
</x-master-layout>